services:
  turtlesim-ros2:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: turtlesim-ros2
    tty: true
    volumes:
      - ./:/home/root
    ports:
      - 2201:2201
      - 6080:6080