services:
  assf-ros2:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: assf-ros2
    tty: true
    volumes:
      - ./:/home/root
    ports:
      - 2201:2201
      - 8888:8888
