services:
  rosdev-ros2:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: rosdev-ros2
    tty: true
    volumes:
      - ./:/root/dev/rosdev
    ports:
      - 2201:2201
      - 6080:6080
      - 8888:8888